name: CI - Mini Library System

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Python setup
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Node.js setup
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install Python deps
      - name: Install Python dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install frontend deps
      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install

      # Run Book Service
      - name: Run Book Service
        run: |
          cd backend/book_service
          nohup python manage.py runserver 8001 &
          sleep 5

      # Run Borrow Service
      - name: Run Borrow Service
        run: |
          cd backend/borrow_service
          nohup python manage.py runserver 8002 &
          sleep 5

      # Run User Service
      - name: Run User Service
        run: |
          cd backend/user_service
          nohup python manage.py runserver 8003 &
          sleep 5

      # Run frontend
      - name: Run React frontend
        run: |
          cd frontend
          nohup yarn start &
          sleep 10

      # Check that services are running
      - name: Test API endpoints
        run: |
          curl http://127.0.0.1:8001/ || exit 1
          curl http://127.0.0.1:8002/ || exit 1
          curl http://127.0.0.1:8003/ || exit 1
